-- Fix Admin Accounts with CORRECT Current Hashes
-- Based on console output: admin password 'mphs2025' generates hash '6tnppr'

-- Step 1: Check current hashes in database
SELECT username, password_hash, role FROM admin_users 
WHERE username IN ('admin', 'boss');

-- Step 2: Update with the ACTUAL hashes being generated by simpleHash()
-- From console log: 'mphs2025' -> '6tnppr'
-- We need to calculate boss hash too

-- For now, let's use the hash from console for admin
UPDATE admin_users 
SET password_hash = '6tnppr', updated_at = NOW()
WHERE username = 'admin';

-- For boss, we need to calculate or get from console
-- Temporary: delete boss and let system recreate
DELETE FROM admin_users WHERE username = 'boss';

-- Step 3: Verify admin hash
SELECT username, password_hash, role FROM admin_users WHERE username = 'admin';

-- Step 4: Now login as admin should work
-- Then use "Urus Admin" to create boss account with correct hash
